mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.0 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.005 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.01 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.015 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.02 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.025 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.03 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.035 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.04 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.045 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.05 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.055 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.06 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.065 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.07 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.075 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.08 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.085 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.09 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.095 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.1 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.105 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.11 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.115 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.12 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.125 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.13 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.135 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.14 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.145 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.15 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.155 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.16 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.165 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.17 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.175 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.18 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.185 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.19 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.195 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.2 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.205 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.21 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.215 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.22 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.225 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.23 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.235 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.24 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.245 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.25 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.255 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.26 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.265 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.27 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.275 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.28 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.285 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.29 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.295 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.3 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.305 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.31 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.315 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.32 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.325 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.33 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.335 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.34 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.345 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.35 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.355 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.36 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.365 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.37 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.375 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.38 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.385 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.39 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.395 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.4 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.405 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.41 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.415 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.42 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.425 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.43 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.435 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.44 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.445 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.45 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.455 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.46 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.465 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.47 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.475 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.48 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.485 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.49 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.495 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
mkdir: cannot create directory ‘data_polariton/’: File exists
	Parameters (η_1, wc): 0.5 3.0
Dimension = 5010
	Memory size of numpy array in (MB, GB): (200.8,0.2)
	Starting eigensolver.
	Starting Average Photonic Excitation.
	Starting Average Matter Excitation.
	Starting Matter Population.
	Starting Matter Population.
