Dimension = 8000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (512.0,0.51)
0.01 1.8
Dimension = 8000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (512.0,0.51)
0.2 1.8
Dimension = 8000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (512.0,0.51)
0.1 1.8
Dimension = 8000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (512.0,0.51)
0.3 1.8
Dimension = 8000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (512.0,0.51)
0.4 1.8
