 Read checkpoint file S_1.chk type G16
 Write formatted file S_1.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 00:51:48 2022
 Aft UFChkP           Fri May 27 00:54:21 2022      153.07 cpu,      153.07 elapsed
 Aft DecCub           Fri May 27 00:54:27 2022        5.89 cpu,        5.89 elapsed
 Aft Density          Fri May 27 00:54:27 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 00:54:27 2022        0.01 cpu,        0.02 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999567625
 Aft DoCube           Fri May 27 00:54:27 2022        0.26 cpu,        0.37 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 00:54:27 2022
 Aft UFChkP           Fri May 27 00:57:00 2022      152.81 cpu,      152.81 elapsed
 Aft DecCub           Fri May 27 00:57:06 2022        5.88 cpu,        5.88 elapsed
 Aft Density          Fri May 27 00:57:06 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 00:57:06 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4122683441
 Aft DoCube           Fri May 27 00:57:06 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_2.chk type G16
 Write formatted file S_2.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 00:57:24 2022
 Aft UFChkP           Fri May 27 00:59:58 2022      153.44 cpu,      153.43 elapsed
 Aft DecCub           Fri May 27 01:00:04 2022        5.90 cpu,        5.90 elapsed
 Aft Density          Fri May 27 01:00:04 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:00:04 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000165174
 Aft DoCube           Fri May 27 01:00:04 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:00:04 2022
 Aft UFChkP           Fri May 27 01:02:38 2022      153.80 cpu,      153.80 elapsed
 Aft DecCub           Fri May 27 01:02:44 2022        5.88 cpu,        5.87 elapsed
 Aft Density          Fri May 27 01:02:44 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:02:44 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4160980437
 Aft DoCube           Fri May 27 01:02:44 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_3.chk type G16
 Write formatted file S_3.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:03:02 2022
 Aft UFChkP           Fri May 27 01:05:35 2022      153.49 cpu,      153.49 elapsed
 Aft DecCub           Fri May 27 01:05:41 2022        5.90 cpu,        5.90 elapsed
 Aft Density          Fri May 27 01:05:41 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:05:41 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000592412
 Aft DoCube           Fri May 27 01:05:41 2022        0.27 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:05:41 2022
 Aft UFChkP           Fri May 27 01:08:14 2022      152.68 cpu,      152.68 elapsed
 Aft DecCub           Fri May 27 01:08:20 2022        5.86 cpu,        5.85 elapsed
 Aft Density          Fri May 27 01:08:20 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:08:20 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4002774536
 Aft DoCube           Fri May 27 01:08:20 2022        0.37 cpu,        0.38 elapsed
 Read checkpoint file S_4.chk type G16
 Write formatted file S_4.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:08:38 2022
 Aft UFChkP           Fri May 27 01:11:11 2022      152.68 cpu,      152.68 elapsed
 Aft DecCub           Fri May 27 01:11:17 2022        5.88 cpu,        5.88 elapsed
 Aft Density          Fri May 27 01:11:17 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:11:17 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000842295
 Aft DoCube           Fri May 27 01:11:17 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:11:17 2022
 Aft UFChkP           Fri May 27 01:13:51 2022      154.04 cpu,      154.05 elapsed
 Aft DecCub           Fri May 27 01:13:57 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 01:13:57 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:13:57 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3980269150
 Aft DoCube           Fri May 27 01:13:57 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_5.chk type G16
 Write formatted file S_5.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:14:15 2022
 Aft UFChkP           Fri May 27 01:16:47 2022      152.24 cpu,      152.24 elapsed
 Aft DecCub           Fri May 27 01:16:53 2022        5.81 cpu,        5.81 elapsed
 Aft Density          Fri May 27 01:16:53 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:16:53 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000245487
 Aft DoCube           Fri May 27 01:16:53 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:16:53 2022
 Aft UFChkP           Fri May 27 01:19:26 2022      153.21 cpu,      153.21 elapsed
 Aft DecCub           Fri May 27 01:19:32 2022        5.88 cpu,        5.88 elapsed
 Aft Density          Fri May 27 01:19:32 2022        0.01 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:19:32 2022        0.00 cpu,        0.01 elapsed
 There are a total of      263552 grid points.
 ElSum from         orbitals=        0.4722610340
 Aft DoCube           Fri May 27 01:19:33 2022        0.59 cpu,        0.58 elapsed
 Read checkpoint file S_6.chk type G16
 Write formatted file S_6.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:19:51 2022
 Aft UFChkP           Fri May 27 01:22:24 2022      153.16 cpu,      153.17 elapsed
 Aft DecCub           Fri May 27 01:22:30 2022        5.92 cpu,        5.91 elapsed
 Aft Density          Fri May 27 01:22:30 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:22:30 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4997869406
 Aft DoCube           Fri May 27 01:22:30 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:22:30 2022
 Aft UFChkP           Fri May 27 01:25:04 2022      153.60 cpu,      153.59 elapsed
 Aft DecCub           Fri May 27 01:25:09 2022        5.93 cpu,        5.93 elapsed
 Aft Density          Fri May 27 01:25:09 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:25:09 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3980081921
 Aft DoCube           Fri May 27 01:25:10 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_7.chk type G16
 Write formatted file S_7.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:25:27 2022
 Aft UFChkP           Fri May 27 01:28:01 2022      153.67 cpu,      153.66 elapsed
 Aft DecCub           Fri May 27 01:28:07 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 01:28:07 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:28:07 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000283486
 Aft DoCube           Fri May 27 01:28:07 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:28:07 2022
 Aft UFChkP           Fri May 27 01:30:41 2022      153.36 cpu,      153.36 elapsed
 Aft DecCub           Fri May 27 01:30:47 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 01:30:47 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:30:47 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4063651958
 Aft DoCube           Fri May 27 01:30:47 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_8.chk type G16
 Write formatted file S_8.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:31:04 2022
 Aft UFChkP           Fri May 27 01:33:37 2022      152.84 cpu,      152.85 elapsed
 Aft DecCub           Fri May 27 01:33:43 2022        5.89 cpu,        5.88 elapsed
 Aft Density          Fri May 27 01:33:43 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:33:43 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4991829373
 Aft DoCube           Fri May 27 01:33:43 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:33:43 2022
 Aft UFChkP           Fri May 27 01:36:16 2022      152.90 cpu,      152.89 elapsed
 Aft DecCub           Fri May 27 01:36:22 2022        5.91 cpu,        5.92 elapsed
 Aft Density          Fri May 27 01:36:22 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:36:22 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3978522218
 Aft DoCube           Fri May 27 01:36:22 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_9.chk type G16
 Write formatted file S_9.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:36:39 2022
 Aft UFChkP           Fri May 27 01:39:12 2022      152.86 cpu,      152.85 elapsed
 Aft DecCub           Fri May 27 01:39:18 2022        5.89 cpu,        5.90 elapsed
 Aft Density          Fri May 27 01:39:18 2022        0.01 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:39:18 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000668388
 Aft DoCube           Fri May 27 01:39:18 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:39:18 2022
 Aft UFChkP           Fri May 27 01:41:52 2022      153.79 cpu,      153.78 elapsed
 Aft DecCub           Fri May 27 01:41:58 2022        5.91 cpu,        5.92 elapsed
 Aft Density          Fri May 27 01:41:58 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:41:58 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3888256531
 Aft DoCube           Fri May 27 01:41:58 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_10.chk type G16
 Write formatted file S_10.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:42:16 2022
 Aft UFChkP           Fri May 27 01:44:49 2022      153.13 cpu,      153.13 elapsed
 Aft DecCub           Fri May 27 01:44:55 2022        5.91 cpu,        5.90 elapsed
 Aft Density          Fri May 27 01:44:55 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:44:55 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999097958
 Aft DoCube           Fri May 27 01:44:55 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:44:55 2022
 Aft UFChkP           Fri May 27 01:47:28 2022      153.41 cpu,      153.41 elapsed
 Aft DecCub           Fri May 27 01:47:34 2022        5.89 cpu,        5.89 elapsed
 Aft Density          Fri May 27 01:47:34 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:47:34 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4003350005
 Aft DoCube           Fri May 27 01:47:35 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_11.chk type G16
 Write formatted file S_11.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:47:51 2022
 Aft UFChkP           Fri May 27 01:50:24 2022      152.83 cpu,      152.84 elapsed
 Aft DecCub           Fri May 27 01:50:30 2022        5.90 cpu,        5.89 elapsed
 Aft Density          Fri May 27 01:50:30 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:50:30 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999445144
 Aft DoCube           Fri May 27 01:50:30 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:50:30 2022
 Aft UFChkP           Fri May 27 01:53:04 2022      153.81 cpu,      153.81 elapsed
 Aft DecCub           Fri May 27 01:53:10 2022        5.93 cpu,        5.93 elapsed
 Aft Density          Fri May 27 01:53:10 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:53:10 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4025422143
 Aft DoCube           Fri May 27 01:53:11 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_12.chk type G16
 Write formatted file S_12.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:53:28 2022
 Aft UFChkP           Fri May 27 01:56:01 2022      152.87 cpu,      152.93 elapsed
 Aft DecCub           Fri May 27 01:56:06 2022        5.89 cpu,        5.89 elapsed
 Aft Density          Fri May 27 01:56:06 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:56:06 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5001258290
 Aft DoCube           Fri May 27 01:56:07 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:56:07 2022
 Aft UFChkP           Fri May 27 01:58:40 2022      153.55 cpu,      153.55 elapsed
 Aft DecCub           Fri May 27 01:58:46 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 01:58:46 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 01:58:46 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3957809159
 Aft DoCube           Fri May 27 01:58:47 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_13.chk type G16
 Write formatted file S_13.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 01:59:04 2022
 Aft UFChkP           Fri May 27 02:01:38 2022      153.55 cpu,      153.54 elapsed
 Aft DecCub           Fri May 27 02:01:44 2022        5.92 cpu,        5.93 elapsed
 Aft Density          Fri May 27 02:01:44 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:01:44 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4996005116
 Aft DoCube           Fri May 27 02:01:44 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:01:44 2022
 Aft UFChkP           Fri May 27 02:04:17 2022      153.15 cpu,      153.15 elapsed
 Aft DecCub           Fri May 27 02:04:23 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 02:04:23 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:04:23 2022        0.00 cpu,        0.01 elapsed
 There are a total of      263552 grid points.
 ElSum from         orbitals=        0.4746750977
 Aft DoCube           Fri May 27 02:04:23 2022        0.58 cpu,        0.58 elapsed
 Read checkpoint file S_14.chk type G16
 Write formatted file S_14.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:04:41 2022
 Aft UFChkP           Fri May 27 02:07:15 2022      153.63 cpu,      153.63 elapsed
 Aft DecCub           Fri May 27 02:07:20 2022        5.90 cpu,        5.90 elapsed
 Aft Density          Fri May 27 02:07:20 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:07:20 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5001305999
 Aft DoCube           Fri May 27 02:07:21 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:07:21 2022
 Aft UFChkP           Fri May 27 02:09:55 2022      153.81 cpu,      153.82 elapsed
 Aft DecCub           Fri May 27 02:10:00 2022        5.94 cpu,        5.93 elapsed
 Aft Density          Fri May 27 02:10:00 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:10:00 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4027680278
 Aft DoCube           Fri May 27 02:10:01 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_15.chk type G16
 Write formatted file S_15.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:10:18 2022
 Aft UFChkP           Fri May 27 02:12:52 2022      153.68 cpu,      153.68 elapsed
 Aft DecCub           Fri May 27 02:12:58 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 02:12:58 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:12:58 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5002237361
 Aft DoCube           Fri May 27 02:12:58 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:12:58 2022
 Aft UFChkP           Fri May 27 02:15:32 2022      153.57 cpu,      153.57 elapsed
 Aft DecCub           Fri May 27 02:15:38 2022        5.91 cpu,        5.90 elapsed
 Aft Density          Fri May 27 02:15:38 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:15:38 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4003001108
 Aft DoCube           Fri May 27 02:15:38 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_16.chk type G16
 Write formatted file S_16.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:15:56 2022
 Aft UFChkP           Fri May 27 02:18:29 2022      153.49 cpu,      153.49 elapsed
 Aft DecCub           Fri May 27 02:18:35 2022        5.89 cpu,        5.88 elapsed
 Aft Density          Fri May 27 02:18:35 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:18:35 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5001293696
 Aft DoCube           Fri May 27 02:18:35 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:18:35 2022
 Aft UFChkP           Fri May 27 02:21:08 2022      152.84 cpu,      152.84 elapsed
 Aft DecCub           Fri May 27 02:21:14 2022        5.89 cpu,        5.89 elapsed
 Aft Density          Fri May 27 02:21:14 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:21:14 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4142779647
 Aft DoCube           Fri May 27 02:21:15 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_17.chk type G16
 Write formatted file S_17.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:21:32 2022
 Aft UFChkP           Fri May 27 02:24:06 2022      153.25 cpu,      153.25 elapsed
 Aft DecCub           Fri May 27 02:24:11 2022        5.88 cpu,        5.88 elapsed
 Aft Density          Fri May 27 02:24:11 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:24:11 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4994912332
 Aft DoCube           Fri May 27 02:24:12 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:24:12 2022
 Aft UFChkP           Fri May 27 02:26:45 2022      153.29 cpu,      153.28 elapsed
 Aft DecCub           Fri May 27 02:26:51 2022        5.88 cpu,        5.89 elapsed
 Aft Density          Fri May 27 02:26:51 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:26:51 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3993881374
 Aft DoCube           Fri May 27 02:26:51 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_18.chk type G16
 Write formatted file S_18.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:27:09 2022
 Aft UFChkP           Fri May 27 02:29:43 2022      153.48 cpu,      153.48 elapsed
 Aft DecCub           Fri May 27 02:29:49 2022        5.90 cpu,        5.90 elapsed
 Aft Density          Fri May 27 02:29:49 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:29:49 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4996855441
 Aft DoCube           Fri May 27 02:29:49 2022        0.27 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:29:49 2022
 Aft UFChkP           Fri May 27 02:32:22 2022      153.36 cpu,      153.36 elapsed
 Aft DecCub           Fri May 27 02:32:28 2022        5.93 cpu,        5.93 elapsed
 Aft Density          Fri May 27 02:32:28 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:32:28 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3939192685
 Aft DoCube           Fri May 27 02:32:28 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_19.chk type G16
 Write formatted file S_19.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:32:47 2022
 Aft UFChkP           Fri May 27 02:35:20 2022      153.69 cpu,      153.69 elapsed
 Aft DecCub           Fri May 27 02:35:26 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 02:35:26 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:35:26 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000518345
 Aft DoCube           Fri May 27 02:35:27 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:35:27 2022
 Aft UFChkP           Fri May 27 02:38:00 2022      153.26 cpu,      153.26 elapsed
 Aft DecCub           Fri May 27 02:38:06 2022        5.90 cpu,        5.90 elapsed
 Aft Density          Fri May 27 02:38:06 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:38:06 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4138158773
 Aft DoCube           Fri May 27 02:38:06 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_20.chk type G16
 Write formatted file S_20.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:38:25 2022
 Aft UFChkP           Fri May 27 02:40:59 2022      153.57 cpu,      153.57 elapsed
 Aft DecCub           Fri May 27 02:41:05 2022        5.93 cpu,        5.93 elapsed
 Aft Density          Fri May 27 02:41:05 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:41:05 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4996834685
 Aft DoCube           Fri May 27 02:41:05 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:41:05 2022
 Aft UFChkP           Fri May 27 02:43:38 2022      153.49 cpu,      153.50 elapsed
 Aft DecCub           Fri May 27 02:43:44 2022        5.93 cpu,        5.91 elapsed
 Aft Density          Fri May 27 02:43:44 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:43:44 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4033050801
 Aft DoCube           Fri May 27 02:43:45 2022        0.38 cpu,        0.38 elapsed
 Read checkpoint file S_21.chk type G16
 Write formatted file S_21.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:44:03 2022
 Aft UFChkP           Fri May 27 02:46:36 2022      153.19 cpu,      153.20 elapsed
 Aft DecCub           Fri May 27 02:46:42 2022        5.92 cpu,        5.90 elapsed
 Aft Density          Fri May 27 02:46:42 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:46:42 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5001387869
 Aft DoCube           Fri May 27 02:46:42 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:46:42 2022
 Aft UFChkP           Fri May 27 02:49:15 2022      153.35 cpu,      153.35 elapsed
 Aft DecCub           Fri May 27 02:49:21 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 02:49:21 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:49:21 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3957270259
 Aft DoCube           Fri May 27 02:49:22 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_22.chk type G16
 Write formatted file S_22.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:49:40 2022
 Aft UFChkP           Fri May 27 02:52:13 2022      153.48 cpu,      153.47 elapsed
 Aft DecCub           Fri May 27 02:52:19 2022        5.90 cpu,        5.91 elapsed
 Aft Density          Fri May 27 02:52:19 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:52:19 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4998143572
 Aft DoCube           Fri May 27 02:52:19 2022        0.27 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:52:19 2022
 Aft UFChkP           Fri May 27 02:54:52 2022      152.87 cpu,      152.87 elapsed
 Aft DecCub           Fri May 27 02:54:58 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 02:54:58 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:54:58 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4424774869
 Aft DoCube           Fri May 27 02:54:59 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_23.chk type G16
 Write formatted file S_23.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:55:16 2022
 Aft UFChkP           Fri May 27 02:57:50 2022      153.65 cpu,      153.65 elapsed
 Aft DecCub           Fri May 27 02:57:56 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 02:57:56 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 02:57:56 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4998934584
 Aft DoCube           Fri May 27 02:57:56 2022        0.27 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 02:57:56 2022
 Aft UFChkP           Fri May 27 03:00:29 2022      152.99 cpu,      152.98 elapsed
 Aft DecCub           Fri May 27 03:00:35 2022        5.89 cpu,        5.89 elapsed
 Aft Density          Fri May 27 03:00:35 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:00:35 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3981712832
 Aft DoCube           Fri May 27 03:00:35 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_24.chk type G16
 Write formatted file S_24.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:00:54 2022
 Aft UFChkP           Fri May 27 03:03:28 2022      153.19 cpu,      153.21 elapsed
 Aft DecCub           Fri May 27 03:03:33 2022        5.92 cpu,        5.91 elapsed
 Aft Density          Fri May 27 03:03:33 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:03:33 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000398414
 Aft DoCube           Fri May 27 03:03:34 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:03:34 2022
 Aft UFChkP           Fri May 27 03:06:07 2022      153.36 cpu,      153.36 elapsed
 Aft DecCub           Fri May 27 03:06:13 2022        5.93 cpu,        5.92 elapsed
 Aft Density          Fri May 27 03:06:13 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:06:13 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4011321761
 Aft DoCube           Fri May 27 03:06:13 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_25.chk type G16
 Write formatted file S_25.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:06:32 2022
 Aft UFChkP           Fri May 27 03:09:05 2022      153.67 cpu,      153.69 elapsed
 Aft DecCub           Fri May 27 03:09:11 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 03:09:11 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:09:11 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4998442091
 Aft DoCube           Fri May 27 03:09:11 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:09:11 2022
 Aft UFChkP           Fri May 27 03:11:45 2022      153.42 cpu,      153.41 elapsed
 Aft DecCub           Fri May 27 03:11:51 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 03:11:51 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:11:51 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3921861457
 Aft DoCube           Fri May 27 03:11:51 2022        0.37 cpu,        0.38 elapsed
 Read checkpoint file S_26.chk type G16
 Write formatted file S_26.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:12:09 2022
 Aft UFChkP           Fri May 27 03:14:43 2022      153.46 cpu,      153.46 elapsed
 Aft DecCub           Fri May 27 03:14:48 2022        5.89 cpu,        5.89 elapsed
 Aft Density          Fri May 27 03:14:48 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:14:48 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000655268
 Aft DoCube           Fri May 27 03:14:49 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:14:49 2022
 Aft UFChkP           Fri May 27 03:17:22 2022      153.44 cpu,      153.44 elapsed
 Aft DecCub           Fri May 27 03:17:28 2022        5.91 cpu,        5.92 elapsed
 Aft Density          Fri May 27 03:17:28 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:17:28 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4004726672
 Aft DoCube           Fri May 27 03:17:28 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_27.chk type G16
 Write formatted file S_27.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:17:46 2022
 Aft UFChkP           Fri May 27 03:20:20 2022      153.11 cpu,      153.13 elapsed
 Aft DecCub           Fri May 27 03:20:26 2022        5.89 cpu,        5.89 elapsed
 Aft Density          Fri May 27 03:20:26 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:20:26 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4996341060
 Aft DoCube           Fri May 27 03:20:26 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:20:26 2022
 Aft UFChkP           Fri May 27 03:22:59 2022      153.39 cpu,      153.39 elapsed
 Aft DecCub           Fri May 27 03:23:05 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 03:23:05 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:23:05 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3925349047
 Aft DoCube           Fri May 27 03:23:05 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_28.chk type G16
 Write formatted file S_28.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:23:24 2022
 Aft UFChkP           Fri May 27 03:25:57 2022      153.45 cpu,      153.46 elapsed
 Aft DecCub           Fri May 27 03:26:03 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 03:26:03 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:26:03 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5001582910
 Aft DoCube           Fri May 27 03:26:03 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:26:03 2022
 Aft UFChkP           Fri May 27 03:28:36 2022      152.94 cpu,      152.94 elapsed
 Aft DecCub           Fri May 27 03:28:42 2022        5.89 cpu,        5.89 elapsed
 Aft Density          Fri May 27 03:28:42 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:28:42 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4156086004
 Aft DoCube           Fri May 27 03:28:42 2022        0.38 cpu,        0.38 elapsed
 Read checkpoint file S_29.chk type G16
 Write formatted file S_29.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:29:00 2022
 Aft UFChkP           Fri May 27 03:31:35 2022      154.52 cpu,      154.53 elapsed
 Aft DecCub           Fri May 27 03:31:41 2022        5.90 cpu,        5.90 elapsed
 Aft Density          Fri May 27 03:31:41 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:31:41 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5001273220
 Aft DoCube           Fri May 27 03:31:41 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:31:41 2022
 Aft UFChkP           Fri May 27 03:34:15 2022      153.44 cpu,      153.44 elapsed
 Aft DecCub           Fri May 27 03:34:20 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 03:34:20 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:34:20 2022        0.01 cpu,        0.01 elapsed
 There are a total of      263552 grid points.
 ElSum from         orbitals=        0.4725013228
 Aft DoCube           Fri May 27 03:34:21 2022        0.58 cpu,        0.58 elapsed
 Read checkpoint file S_30.chk type G16
 Write formatted file S_30.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:34:39 2022
 Aft UFChkP           Fri May 27 03:37:12 2022      153.40 cpu,      153.42 elapsed
 Aft DecCub           Fri May 27 03:37:18 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 03:37:18 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:37:18 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5001611719
 Aft DoCube           Fri May 27 03:37:18 2022        0.27 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:37:19 2022
 Aft UFChkP           Fri May 27 03:39:51 2022      152.44 cpu,      152.43 elapsed
 Aft DecCub           Fri May 27 03:39:57 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 03:39:57 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:39:57 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4285559099
 Aft DoCube           Fri May 27 03:39:57 2022        0.38 cpu,        0.37 elapsed
 Read checkpoint file S_31.chk type G16
 Write formatted file S_31.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:40:24 2022
 Aft UFChkP           Fri May 27 03:42:57 2022      153.00 cpu,      153.02 elapsed
 Aft DecCub           Fri May 27 03:43:03 2022        5.96 cpu,        5.95 elapsed
 Aft Density          Fri May 27 03:43:03 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:43:03 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000051586
 Aft DoCube           Fri May 27 03:43:03 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:43:03 2022
 Aft UFChkP           Fri May 27 03:45:36 2022      153.52 cpu,      153.52 elapsed
 Aft DecCub           Fri May 27 03:45:42 2022        5.98 cpu,        5.98 elapsed
 Aft Density          Fri May 27 03:45:42 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:45:42 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4041038464
 Aft DoCube           Fri May 27 03:45:43 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_32.chk type G16
 Write formatted file S_32.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:46:05 2022
 Aft UFChkP           Fri May 27 03:48:38 2022      153.48 cpu,      153.50 elapsed
 Aft DecCub           Fri May 27 03:48:44 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 03:48:44 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:48:44 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5002003343
 Aft DoCube           Fri May 27 03:48:45 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:48:45 2022
 Aft UFChkP           Fri May 27 03:51:18 2022      153.71 cpu,      153.71 elapsed
 Aft DecCub           Fri May 27 03:51:24 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 03:51:24 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:51:24 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4193034842
 Aft DoCube           Fri May 27 03:51:25 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_33.chk type G16
 Write formatted file S_33.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:51:43 2022
 Aft UFChkP           Fri May 27 03:54:17 2022      153.59 cpu,      153.69 elapsed
 Aft DecCub           Fri May 27 03:54:23 2022        5.91 cpu,        5.92 elapsed
 Aft Density          Fri May 27 03:54:23 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:54:23 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4998718812
 Aft DoCube           Fri May 27 03:54:23 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:54:23 2022
 Aft UFChkP           Fri May 27 03:56:56 2022      153.40 cpu,      153.40 elapsed
 Aft DecCub           Fri May 27 03:57:02 2022        5.91 cpu,        5.92 elapsed
 Aft Density          Fri May 27 03:57:02 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 03:57:02 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4051707492
 Aft DoCube           Fri May 27 03:57:03 2022        0.38 cpu,        0.38 elapsed
 Read checkpoint file S_34.chk type G16
 Write formatted file S_34.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 03:57:21 2022
 Aft UFChkP           Fri May 27 03:59:54 2022      153.12 cpu,      153.23 elapsed
 Aft DecCub           Fri May 27 04:00:00 2022        5.90 cpu,        5.89 elapsed
 Aft Density          Fri May 27 04:00:00 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:00:00 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5003466060
 Aft DoCube           Fri May 27 04:00:00 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:00:00 2022
 Aft UFChkP           Fri May 27 04:02:33 2022      152.94 cpu,      152.94 elapsed
 Aft DecCub           Fri May 27 04:02:39 2022        5.88 cpu,        5.87 elapsed
 Aft Density          Fri May 27 04:02:39 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:02:39 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4040679707
 Aft DoCube           Fri May 27 04:02:39 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_35.chk type G16
 Write formatted file S_35.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:02:57 2022
 Aft UFChkP           Fri May 27 04:05:31 2022      154.30 cpu,      154.34 elapsed
 Aft DecCub           Fri May 27 04:05:37 2022        5.93 cpu,        5.93 elapsed
 Aft Density          Fri May 27 04:05:37 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:05:37 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5003312634
 Aft DoCube           Fri May 27 04:05:37 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:05:37 2022
 Aft UFChkP           Fri May 27 04:08:11 2022      153.11 cpu,      153.11 elapsed
 Aft DecCub           Fri May 27 04:08:16 2022        5.88 cpu,        5.88 elapsed
 Aft Density          Fri May 27 04:08:16 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:08:16 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3947687831
 Aft DoCube           Fri May 27 04:08:17 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_36.chk type G16
 Write formatted file S_36.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:08:34 2022
 Aft UFChkP           Fri May 27 04:11:08 2022      153.85 cpu,      153.89 elapsed
 Aft DecCub           Fri May 27 04:11:14 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 04:11:14 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:11:14 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4993638855
 Aft DoCube           Fri May 27 04:11:15 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:11:15 2022
 Aft UFChkP           Fri May 27 04:13:48 2022      153.19 cpu,      153.19 elapsed
 Aft DecCub           Fri May 27 04:13:54 2022        5.91 cpu,        5.90 elapsed
 Aft Density          Fri May 27 04:13:54 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:13:54 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4143520197
 Aft DoCube           Fri May 27 04:13:54 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_37.chk type G16
 Write formatted file S_37.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:14:12 2022
 Aft UFChkP           Fri May 27 04:16:45 2022      153.41 cpu,      153.45 elapsed
 Aft DecCub           Fri May 27 04:16:51 2022        5.91 cpu,        5.92 elapsed
 Aft Density          Fri May 27 04:16:51 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:16:51 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000545547
 Aft DoCube           Fri May 27 04:16:52 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:16:52 2022
 Aft UFChkP           Fri May 27 04:19:25 2022      153.64 cpu,      153.64 elapsed
 Aft DecCub           Fri May 27 04:19:31 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 04:19:31 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:19:31 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3983645673
 Aft DoCube           Fri May 27 04:19:31 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_38.chk type G16
 Write formatted file S_38.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:19:49 2022
 Aft UFChkP           Fri May 27 04:22:23 2022      153.87 cpu,      153.88 elapsed
 Aft DecCub           Fri May 27 04:22:29 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 04:22:29 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:22:29 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000929252
 Aft DoCube           Fri May 27 04:22:29 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:22:29 2022
 Aft UFChkP           Fri May 27 04:25:03 2022      153.38 cpu,      153.44 elapsed
 Aft DecCub           Fri May 27 04:25:09 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 04:25:09 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:25:09 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3964337180
 Aft DoCube           Fri May 27 04:25:09 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_39.chk type G16
 Write formatted file S_39.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:25:27 2022
 Aft UFChkP           Fri May 27 04:28:01 2022      153.73 cpu,      153.76 elapsed
 Aft DecCub           Fri May 27 04:28:07 2022        5.92 cpu,        5.91 elapsed
 Aft Density          Fri May 27 04:28:07 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:28:07 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000377800
 Aft DoCube           Fri May 27 04:28:07 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:28:07 2022
 Aft UFChkP           Fri May 27 04:30:40 2022      152.74 cpu,      152.74 elapsed
 Aft DecCub           Fri May 27 04:30:46 2022        5.89 cpu,        5.89 elapsed
 Aft Density          Fri May 27 04:30:46 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:30:46 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4278653181
 Aft DoCube           Fri May 27 04:30:46 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_40.chk type G16
 Write formatted file S_40.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:31:04 2022
 Aft UFChkP           Fri May 27 04:33:38 2022      153.79 cpu,      153.81 elapsed
 Aft DecCub           Fri May 27 04:33:44 2022        5.93 cpu,        5.93 elapsed
 Aft Density          Fri May 27 04:33:44 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:33:44 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000791921
 Aft DoCube           Fri May 27 04:33:44 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:33:44 2022
 Aft UFChkP           Fri May 27 04:36:18 2022      153.54 cpu,      153.61 elapsed
 Aft DecCub           Fri May 27 04:36:24 2022        5.90 cpu,        5.91 elapsed
 Aft Density          Fri May 27 04:36:24 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:36:24 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4327802844
 Aft DoCube           Fri May 27 04:36:24 2022        0.39 cpu,        0.38 elapsed
 Read checkpoint file S_41.chk type G16
 Write formatted file S_41.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:36:42 2022
 Aft UFChkP           Fri May 27 04:39:16 2022      153.59 cpu,      153.60 elapsed
 Aft DecCub           Fri May 27 04:39:22 2022        5.92 cpu,        5.93 elapsed
 Aft Density          Fri May 27 04:39:22 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:39:22 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4993975287
 Aft DoCube           Fri May 27 04:39:22 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:39:22 2022
 Aft UFChkP           Fri May 27 04:41:55 2022      153.52 cpu,      153.52 elapsed
 Aft DecCub           Fri May 27 04:42:01 2022        5.92 cpu,        5.91 elapsed
 Aft Density          Fri May 27 04:42:01 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:42:01 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3976352585
 Aft DoCube           Fri May 27 04:42:02 2022        0.38 cpu,        0.38 elapsed
 Read checkpoint file S_42.chk type G16
 Write formatted file S_42.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:42:20 2022
 Aft UFChkP           Fri May 27 04:44:54 2022      153.62 cpu,      153.68 elapsed
 Aft DecCub           Fri May 27 04:45:00 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 04:45:00 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:45:00 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5001686963
 Aft DoCube           Fri May 27 04:45:00 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:45:00 2022
 Aft UFChkP           Fri May 27 04:47:33 2022      153.42 cpu,      153.42 elapsed
 Aft DecCub           Fri May 27 04:47:39 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 04:47:39 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:47:39 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4013723585
 Aft DoCube           Fri May 27 04:47:40 2022        0.38 cpu,        0.38 elapsed
 Read checkpoint file S_43.chk type G16
 Write formatted file S_43.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:47:58 2022
 Aft UFChkP           Fri May 27 04:50:34 2022      155.85 cpu,      156.01 elapsed
 Aft DecCub           Fri May 27 04:50:39 2022        5.93 cpu,        5.92 elapsed
 Aft Density          Fri May 27 04:50:39 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:50:39 2022        0.01 cpu,        0.01 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5001876516
 Aft DoCube           Fri May 27 04:50:40 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:50:40 2022
 Aft UFChkP           Fri May 27 04:53:13 2022      153.33 cpu,      153.60 elapsed
 Aft DecCub           Fri May 27 04:53:19 2022        5.92 cpu,        5.91 elapsed
 Aft Density          Fri May 27 04:53:19 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:53:19 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4240498528
 Aft DoCube           Fri May 27 04:53:20 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_44.chk type G16
 Write formatted file S_44.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:53:37 2022
 Aft UFChkP           Fri May 27 04:56:11 2022      153.75 cpu,      154.01 elapsed
 Aft DecCub           Fri May 27 04:56:17 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 04:56:17 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:56:17 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4997559258
 Aft DoCube           Fri May 27 04:56:18 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:56:18 2022
 Aft UFChkP           Fri May 27 04:58:51 2022      153.56 cpu,      153.83 elapsed
 Aft DecCub           Fri May 27 04:58:57 2022        5.92 cpu,        5.91 elapsed
 Aft Density          Fri May 27 04:58:57 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 04:58:57 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3988560933
 Aft DoCube           Fri May 27 04:58:58 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_45.chk type G16
 Write formatted file S_45.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 04:59:16 2022
 Aft UFChkP           Fri May 27 05:01:49 2022      153.42 cpu,      153.58 elapsed
 Aft DecCub           Fri May 27 05:01:55 2022        5.90 cpu,        5.90 elapsed
 Aft Density          Fri May 27 05:01:55 2022        0.01 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:01:55 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4991109572
 Aft DoCube           Fri May 27 05:01:56 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:01:56 2022
 Aft UFChkP           Fri May 27 05:04:29 2022      153.10 cpu,      153.55 elapsed
 Aft DecCub           Fri May 27 05:04:35 2022        5.91 cpu,        5.92 elapsed
 Aft Density          Fri May 27 05:04:35 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:04:35 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3937317981
 Aft DoCube           Fri May 27 05:04:35 2022        0.38 cpu,        0.37 elapsed
 Read checkpoint file S_46.chk type G16
 Write formatted file S_46.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:04:53 2022
 Aft UFChkP           Fri May 27 05:07:29 2022      153.77 cpu,      155.31 elapsed
 Aft DecCub           Fri May 27 05:07:35 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 05:07:35 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:07:35 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4995429702
 Aft DoCube           Fri May 27 05:07:35 2022        0.25 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:07:35 2022
 Aft UFChkP           Fri May 27 05:10:09 2022      153.46 cpu,      153.75 elapsed
 Aft DecCub           Fri May 27 05:10:15 2022        5.93 cpu,        5.92 elapsed
 Aft Density          Fri May 27 05:10:15 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:10:15 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4143950199
 Aft DoCube           Fri May 27 05:10:15 2022        0.37 cpu,        0.38 elapsed
 Read checkpoint file S_47.chk type G16
 Write formatted file S_47.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:10:33 2022
 Aft UFChkP           Fri May 27 05:13:07 2022      153.88 cpu,      154.29 elapsed
 Aft DecCub           Fri May 27 05:13:13 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 05:13:13 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:13:13 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000844724
 Aft DoCube           Fri May 27 05:13:13 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:13:13 2022
 Aft UFChkP           Fri May 27 05:15:46 2022      153.28 cpu,      153.27 elapsed
 Aft DecCub           Fri May 27 05:15:52 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 05:15:52 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:15:52 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4108895537
 Aft DoCube           Fri May 27 05:15:53 2022        0.37 cpu,        0.37 elapsed
 Read checkpoint file S_48.chk type G16
 Write formatted file S_48.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:16:11 2022
 Aft UFChkP           Fri May 27 05:18:46 2022      153.63 cpu,      155.05 elapsed
 Aft DecCub           Fri May 27 05:18:52 2022        5.92 cpu,        5.92 elapsed
 Aft Density          Fri May 27 05:18:52 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:18:52 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000358424
 Aft DoCube           Fri May 27 05:18:52 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:18:52 2022
 Aft UFChkP           Fri May 27 05:21:26 2022      153.54 cpu,      153.86 elapsed
 Aft DecCub           Fri May 27 05:21:32 2022        5.90 cpu,        5.90 elapsed
 Aft Density          Fri May 27 05:21:32 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:21:32 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4133024095
 Aft DoCube           Fri May 27 05:21:32 2022        0.37 cpu,        0.38 elapsed
 Read checkpoint file S_49.chk type G16
 Write formatted file S_49.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:21:50 2022
 Aft UFChkP           Fri May 27 05:24:24 2022      152.48 cpu,      154.14 elapsed
 Aft DecCub           Fri May 27 05:24:30 2022        5.88 cpu,        5.88 elapsed
 Aft Density          Fri May 27 05:24:30 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:24:30 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999388225
 Aft DoCube           Fri May 27 05:24:30 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:24:30 2022
 Aft UFChkP           Fri May 27 05:27:04 2022      153.18 cpu,      153.18 elapsed
 Aft DecCub           Fri May 27 05:27:10 2022        5.91 cpu,        5.91 elapsed
 Aft Density          Fri May 27 05:27:10 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:27:10 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4120447244
 Aft DoCube           Fri May 27 05:27:10 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_50.chk type G16
 Write formatted file S_50.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:27:28 2022
 Aft UFChkP           Fri May 27 05:30:02 2022      152.97 cpu,      153.96 elapsed
 Aft DecCub           Fri May 27 05:30:08 2022        5.89 cpu,        5.90 elapsed
 Aft Density          Fri May 27 05:30:08 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:30:08 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4992107588
 Aft DoCube           Fri May 27 05:30:08 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:30:08 2022
 Aft UFChkP           Fri May 27 05:32:40 2022      151.38 cpu,      151.38 elapsed
 Aft DecCub           Fri May 27 05:32:45 2022        5.79 cpu,        5.80 elapsed
 Aft Density          Fri May 27 05:32:45 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:32:45 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4030186135
 Aft DoCube           Fri May 27 05:32:46 2022        0.36 cpu,        0.37 elapsed
 Read checkpoint file S_51.chk type G16
 Write formatted file S_51.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:33:04 2022
 Aft UFChkP           Fri May 27 05:35:39 2022      151.21 cpu,      154.56 elapsed
 Aft DecCub           Fri May 27 05:35:44 2022        5.66 cpu,        5.66 elapsed
 Aft Density          Fri May 27 05:35:44 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:35:44 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4993098793
 Aft DoCube           Fri May 27 05:35:44 2022        0.25 cpu,        0.25 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:35:44 2022
 Aft UFChkP           Fri May 27 05:38:11 2022      146.16 cpu,      146.65 elapsed
 Aft DecCub           Fri May 27 05:38:17 2022        5.64 cpu,        5.76 elapsed
 Aft Density          Fri May 27 05:38:17 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:38:17 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4004814623
 Aft DoCube           Fri May 27 05:38:17 2022        0.35 cpu,        0.36 elapsed
 Read checkpoint file S_52.chk type G16
 Write formatted file S_52.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:38:35 2022
 Aft UFChkP           Fri May 27 05:41:02 2022      145.75 cpu,      146.94 elapsed
 Aft DecCub           Fri May 27 05:41:07 2022        5.61 cpu,        5.62 elapsed
 Aft Density          Fri May 27 05:41:07 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:41:07 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999646031
 Aft DoCube           Fri May 27 05:41:08 2022        0.25 cpu,        0.25 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:41:08 2022
 Aft UFChkP           Fri May 27 05:43:33 2022      145.76 cpu,      145.76 elapsed
 Aft DecCub           Fri May 27 05:43:39 2022        5.63 cpu,        5.62 elapsed
 Aft Density          Fri May 27 05:43:39 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:43:39 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4035102669
 Aft DoCube           Fri May 27 05:43:39 2022        0.37 cpu,        0.36 elapsed
 Read checkpoint file S_53.chk type G16
 Write formatted file S_53.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:43:57 2022
 Aft UFChkP           Fri May 27 05:46:24 2022      145.51 cpu,      146.95 elapsed
 Aft DecCub           Fri May 27 05:46:30 2022        5.60 cpu,        5.61 elapsed
 Aft Density          Fri May 27 05:46:30 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:46:30 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4982239830
 Aft DoCube           Fri May 27 05:46:30 2022        0.26 cpu,        0.26 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:46:30 2022
 Aft UFChkP           Fri May 27 05:48:51 2022      140.63 cpu,      140.63 elapsed
 Aft DecCub           Fri May 27 05:48:56 2022        5.23 cpu,        5.24 elapsed
 Aft Density          Fri May 27 05:48:56 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:48:56 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4286615971
 Aft DoCube           Fri May 27 05:48:56 2022        0.36 cpu,        0.36 elapsed
 Read checkpoint file S_54.chk type G16
 Write formatted file S_54.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:49:14 2022
 Aft UFChkP           Fri May 27 05:51:31 2022      136.42 cpu,      137.62 elapsed
 Aft DecCub           Fri May 27 05:51:37 2022        5.25 cpu,        5.26 elapsed
 Aft Density          Fri May 27 05:51:37 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:51:37 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5006162817
 Aft DoCube           Fri May 27 05:51:37 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:51:37 2022
 Aft UFChkP           Fri May 27 05:53:53 2022      136.40 cpu,      136.40 elapsed
 Aft DecCub           Fri May 27 05:53:58 2022        5.26 cpu,        5.26 elapsed
 Aft Density          Fri May 27 05:53:58 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:53:59 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4037889244
 Aft DoCube           Fri May 27 05:53:59 2022        0.35 cpu,        0.34 elapsed
 Read checkpoint file S_55.chk type G16
 Write formatted file S_55.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:54:16 2022
 Aft UFChkP           Fri May 27 05:56:34 2022      136.60 cpu,      137.45 elapsed
 Aft DecCub           Fri May 27 05:56:39 2022        5.27 cpu,        5.27 elapsed
 Aft Density          Fri May 27 05:56:39 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:56:39 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5004046276
 Aft DoCube           Fri May 27 05:56:39 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:56:39 2022
 Aft UFChkP           Fri May 27 05:58:56 2022      136.19 cpu,      136.31 elapsed
 Aft DecCub           Fri May 27 05:59:01 2022        5.26 cpu,        5.25 elapsed
 Aft Density          Fri May 27 05:59:01 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 05:59:01 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4353652849
 Aft DoCube           Fri May 27 05:59:01 2022        0.35 cpu,        0.36 elapsed
 Read checkpoint file S_56.chk type G16
 Write formatted file S_56.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 05:59:20 2022
 Aft UFChkP           Fri May 27 06:01:39 2022      135.97 cpu,      139.04 elapsed
 Aft DecCub           Fri May 27 06:01:44 2022        5.24 cpu,        5.24 elapsed
 Aft Density          Fri May 27 06:01:44 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:01:44 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4995367737
 Aft DoCube           Fri May 27 06:01:44 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:01:44 2022
 Aft UFChkP           Fri May 27 06:04:00 2022      136.43 cpu,      136.43 elapsed
 Aft DecCub           Fri May 27 06:04:06 2022        5.27 cpu,        5.27 elapsed
 Aft Density          Fri May 27 06:04:06 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:04:06 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4066288486
 Aft DoCube           Fri May 27 06:04:06 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_57.chk type G16
 Write formatted file S_57.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:04:23 2022
 Aft UFChkP           Fri May 27 06:06:40 2022      136.35 cpu,      136.53 elapsed
 Aft DecCub           Fri May 27 06:06:45 2022        5.25 cpu,        5.26 elapsed
 Aft Density          Fri May 27 06:06:45 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:06:45 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4998358087
 Aft DoCube           Fri May 27 06:06:45 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:06:45 2022
 Aft UFChkP           Fri May 27 06:09:02 2022      136.13 cpu,      136.80 elapsed
 Aft DecCub           Fri May 27 06:09:07 2022        5.24 cpu,        5.24 elapsed
 Aft Density          Fri May 27 06:09:07 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:09:07 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3943886480
 Aft DoCube           Fri May 27 06:09:08 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_58.chk type G16
 Write formatted file S_58.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:09:25 2022
 Aft UFChkP           Fri May 27 06:11:41 2022      133.53 cpu,      135.77 elapsed
 Aft DecCub           Fri May 27 06:11:46 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 06:11:46 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:11:46 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4996995627
 Aft DoCube           Fri May 27 06:11:46 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:11:46 2022
 Aft UFChkP           Fri May 27 06:13:59 2022      132.78 cpu,      132.78 elapsed
 Aft DecCub           Fri May 27 06:14:04 2022        5.12 cpu,        5.11 elapsed
 Aft Density          Fri May 27 06:14:04 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:14:04 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3951524601
 Aft DoCube           Fri May 27 06:14:04 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_59.chk type G16
 Write formatted file S_59.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:14:21 2022
 Aft UFChkP           Fri May 27 06:16:35 2022      133.37 cpu,      134.50 elapsed
 Aft DecCub           Fri May 27 06:16:40 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 06:16:40 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:16:40 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999695974
 Aft DoCube           Fri May 27 06:16:41 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:16:41 2022
 Aft UFChkP           Fri May 27 06:18:54 2022      133.53 cpu,      133.52 elapsed
 Aft DecCub           Fri May 27 06:18:59 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 06:18:59 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:18:59 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3983469678
 Aft DoCube           Fri May 27 06:19:00 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_60.chk type G16
 Write formatted file S_60.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:19:17 2022
 Aft UFChkP           Fri May 27 06:21:31 2022      133.53 cpu,      134.56 elapsed
 Aft DecCub           Fri May 27 06:21:36 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 06:21:36 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:21:36 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000791838
 Aft DoCube           Fri May 27 06:21:37 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:21:37 2022
 Aft UFChkP           Fri May 27 06:23:50 2022      133.25 cpu,      133.32 elapsed
 Aft DecCub           Fri May 27 06:23:55 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 06:23:55 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:23:55 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4000470096
 Aft DoCube           Fri May 27 06:23:55 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_61.chk type G16
 Write formatted file S_61.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:24:12 2022
 Aft UFChkP           Fri May 27 06:26:26 2022      133.29 cpu,      134.05 elapsed
 Aft DecCub           Fri May 27 06:26:31 2022        5.14 cpu,        5.15 elapsed
 Aft Density          Fri May 27 06:26:31 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:26:31 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5001141676
 Aft DoCube           Fri May 27 06:26:31 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:26:31 2022
 Aft UFChkP           Fri May 27 06:28:44 2022      133.20 cpu,      133.20 elapsed
 Aft DecCub           Fri May 27 06:28:49 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 06:28:49 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:28:49 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4107398225
 Aft DoCube           Fri May 27 06:28:50 2022        0.35 cpu,        0.34 elapsed
 Read checkpoint file S_62.chk type G16
 Write formatted file S_62.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:29:06 2022
 Aft UFChkP           Fri May 27 06:31:20 2022      133.51 cpu,      133.69 elapsed
 Aft DecCub           Fri May 27 06:31:25 2022        5.13 cpu,        5.14 elapsed
 Aft Density          Fri May 27 06:31:25 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:31:25 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000933807
 Aft DoCube           Fri May 27 06:31:25 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:31:25 2022
 Aft UFChkP           Fri May 27 06:33:39 2022      133.31 cpu,      133.64 elapsed
 Aft DecCub           Fri May 27 06:33:44 2022        5.12 cpu,        5.13 elapsed
 Aft Density          Fri May 27 06:33:44 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:33:44 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3932551930
 Aft DoCube           Fri May 27 06:33:44 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_63.chk type G16
 Write formatted file S_63.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:34:00 2022
 Aft UFChkP           Fri May 27 06:36:15 2022      133.69 cpu,      134.90 elapsed
 Aft DecCub           Fri May 27 06:36:20 2022        5.16 cpu,        5.15 elapsed
 Aft Density          Fri May 27 06:36:20 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:36:20 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4989017890
 Aft DoCube           Fri May 27 06:36:20 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:36:20 2022
 Aft UFChkP           Fri May 27 06:38:33 2022      132.79 cpu,      132.84 elapsed
 Aft DecCub           Fri May 27 06:38:38 2022        5.11 cpu,        5.12 elapsed
 Aft Density          Fri May 27 06:38:38 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:38:38 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4068729849
 Aft DoCube           Fri May 27 06:38:38 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_64.chk type G16
 Write formatted file S_64.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:38:54 2022
 Aft UFChkP           Fri May 27 06:41:09 2022      133.35 cpu,      134.67 elapsed
 Aft DecCub           Fri May 27 06:41:14 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 06:41:14 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:41:14 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5001811952
 Aft DoCube           Fri May 27 06:41:14 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:41:14 2022
 Aft UFChkP           Fri May 27 06:43:27 2022      132.89 cpu,      132.93 elapsed
 Aft DecCub           Fri May 27 06:43:32 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 06:43:32 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:43:32 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4004075341
 Aft DoCube           Fri May 27 06:43:33 2022        0.33 cpu,        0.34 elapsed
 Read checkpoint file S_65.chk type G16
 Write formatted file S_65.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:43:49 2022
 Aft UFChkP           Fri May 27 06:46:03 2022      133.24 cpu,      134.45 elapsed
 Aft DecCub           Fri May 27 06:46:08 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 06:46:08 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:46:08 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5002233049
 Aft DoCube           Fri May 27 06:46:09 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:46:09 2022
 Aft UFChkP           Fri May 27 06:48:22 2022      133.11 cpu,      133.15 elapsed
 Aft DecCub           Fri May 27 06:48:27 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 06:48:27 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:48:27 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4174511225
 Aft DoCube           Fri May 27 06:48:27 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_66.chk type G16
 Write formatted file S_66.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:48:43 2022
 Aft UFChkP           Fri May 27 06:50:57 2022      133.18 cpu,      133.80 elapsed
 Aft DecCub           Fri May 27 06:51:02 2022        5.15 cpu,        5.14 elapsed
 Aft Density          Fri May 27 06:51:02 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:51:02 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000556656
 Aft DoCube           Fri May 27 06:51:02 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:51:02 2022
 Aft UFChkP           Fri May 27 06:53:15 2022      133.17 cpu,      133.19 elapsed
 Aft DecCub           Fri May 27 06:53:20 2022        5.14 cpu,        5.13 elapsed
 Aft Density          Fri May 27 06:53:20 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:53:20 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4006002935
 Aft DoCube           Fri May 27 06:53:21 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_67.chk type G16
 Write formatted file S_67.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:53:36 2022
 Aft UFChkP           Fri May 27 06:55:49 2022      132.93 cpu,      133.20 elapsed
 Aft DecCub           Fri May 27 06:55:54 2022        5.12 cpu,        5.12 elapsed
 Aft Density          Fri May 27 06:55:54 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:55:54 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5003790144
 Aft DoCube           Fri May 27 06:55:55 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:55:55 2022
 Aft UFChkP           Fri May 27 06:58:08 2022      133.57 cpu,      133.58 elapsed
 Aft DecCub           Fri May 27 06:58:13 2022        5.17 cpu,        5.16 elapsed
 Aft Density          Fri May 27 06:58:13 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 06:58:13 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4118004254
 Aft DoCube           Fri May 27 06:58:14 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_68.chk type G16
 Write formatted file S_68.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 06:58:30 2022
 Aft UFChkP           Fri May 27 07:00:43 2022      133.08 cpu,      133.80 elapsed
 Aft DecCub           Fri May 27 07:00:48 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 07:00:48 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:00:48 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999698121
 Aft DoCube           Fri May 27 07:00:49 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:00:49 2022
 Aft UFChkP           Fri May 27 07:03:02 2022      133.31 cpu,      133.31 elapsed
 Aft DecCub           Fri May 27 07:03:07 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 07:03:07 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:03:07 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4013200191
 Aft DoCube           Fri May 27 07:03:07 2022        0.35 cpu,        0.34 elapsed
 Read checkpoint file S_69.chk type G16
 Write formatted file S_69.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:03:23 2022
 Aft UFChkP           Fri May 27 07:05:37 2022      132.93 cpu,      134.17 elapsed
 Aft DecCub           Fri May 27 07:05:42 2022        5.11 cpu,        5.12 elapsed
 Aft Density          Fri May 27 07:05:43 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:05:43 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5004687524
 Aft DoCube           Fri May 27 07:05:43 2022        0.25 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:05:43 2022
 Aft UFChkP           Fri May 27 07:07:56 2022      133.21 cpu,      133.21 elapsed
 Aft DecCub           Fri May 27 07:08:01 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 07:08:01 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:08:01 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4100436975
 Aft DoCube           Fri May 27 07:08:01 2022        0.33 cpu,        0.34 elapsed
 Read checkpoint file S_70.chk type G16
 Write formatted file S_70.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:08:17 2022
 Aft UFChkP           Fri May 27 07:10:31 2022      133.27 cpu,      134.19 elapsed
 Aft DecCub           Fri May 27 07:10:36 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 07:10:36 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:10:36 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5006823318
 Aft DoCube           Fri May 27 07:10:37 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:10:37 2022
 Aft UFChkP           Fri May 27 07:12:50 2022      133.41 cpu,      133.47 elapsed
 Aft DecCub           Fri May 27 07:12:55 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 07:12:55 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:12:55 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4011138479
 Aft DoCube           Fri May 27 07:12:56 2022        0.33 cpu,        0.34 elapsed
 Read checkpoint file S_71.chk type G16
 Write formatted file S_71.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:13:11 2022
 Aft UFChkP           Fri May 27 07:15:26 2022      133.41 cpu,      134.96 elapsed
 Aft DecCub           Fri May 27 07:15:31 2022        5.16 cpu,        5.16 elapsed
 Aft Density          Fri May 27 07:15:31 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:15:31 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999232453
 Aft DoCube           Fri May 27 07:15:32 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:15:32 2022
 Aft UFChkP           Fri May 27 07:17:44 2022      132.66 cpu,      132.66 elapsed
 Aft DecCub           Fri May 27 07:17:49 2022        5.12 cpu,        5.11 elapsed
 Aft Density          Fri May 27 07:17:49 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:17:49 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4097871012
 Aft DoCube           Fri May 27 07:17:50 2022        0.33 cpu,        0.34 elapsed
 Read checkpoint file S_72.chk type G16
 Write formatted file S_72.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:18:05 2022
 Aft UFChkP           Fri May 27 07:20:19 2022      133.47 cpu,      134.08 elapsed
 Aft DecCub           Fri May 27 07:20:25 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 07:20:25 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:20:25 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5007565280
 Aft DoCube           Fri May 27 07:20:25 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:20:25 2022
 Aft UFChkP           Fri May 27 07:22:38 2022      133.07 cpu,      133.14 elapsed
 Aft DecCub           Fri May 27 07:22:43 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 07:22:43 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:22:43 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4129946784
 Aft DoCube           Fri May 27 07:22:43 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_73.chk type G16
 Write formatted file S_73.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:22:59 2022
 Aft UFChkP           Fri May 27 07:25:14 2022      133.16 cpu,      134.83 elapsed
 Aft DecCub           Fri May 27 07:25:19 2022        5.11 cpu,        5.12 elapsed
 Aft Density          Fri May 27 07:25:19 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:25:19 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4996791635
 Aft DoCube           Fri May 27 07:25:19 2022        0.25 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:25:19 2022
 Aft UFChkP           Fri May 27 07:27:32 2022      132.94 cpu,      132.94 elapsed
 Aft DecCub           Fri May 27 07:27:37 2022        5.10 cpu,        5.10 elapsed
 Aft Density          Fri May 27 07:27:37 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:27:37 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4094889056
 Aft DoCube           Fri May 27 07:27:38 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_74.chk type G16
 Write formatted file S_74.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:27:53 2022
 Aft UFChkP           Fri May 27 07:30:07 2022      133.22 cpu,      133.92 elapsed
 Aft DecCub           Fri May 27 07:30:13 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 07:30:13 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:30:13 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999595895
 Aft DoCube           Fri May 27 07:30:13 2022        0.25 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:30:13 2022
 Aft UFChkP           Fri May 27 07:32:26 2022      133.23 cpu,      133.23 elapsed
 Aft DecCub           Fri May 27 07:32:31 2022        5.11 cpu,        5.11 elapsed
 Aft Density          Fri May 27 07:32:31 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:32:31 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4128341595
 Aft DoCube           Fri May 27 07:32:31 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_75.chk type G16
 Write formatted file S_75.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:32:47 2022
 Aft UFChkP           Fri May 27 07:35:01 2022      133.20 cpu,      133.74 elapsed
 Aft DecCub           Fri May 27 07:35:06 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 07:35:06 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:35:06 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999903566
 Aft DoCube           Fri May 27 07:35:06 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:35:06 2022
 Aft UFChkP           Fri May 27 07:37:19 2022      133.31 cpu,      133.31 elapsed
 Aft DecCub           Fri May 27 07:37:25 2022        5.14 cpu,        5.13 elapsed
 Aft Density          Fri May 27 07:37:25 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:37:25 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4139922273
 Aft DoCube           Fri May 27 07:37:25 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_76.chk type G16
 Write formatted file S_76.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:37:41 2022
 Aft UFChkP           Fri May 27 07:39:54 2022      133.04 cpu,      133.68 elapsed
 Aft DecCub           Fri May 27 07:40:00 2022        5.13 cpu,        5.14 elapsed
 Aft Density          Fri May 27 07:40:00 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:40:00 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5004901802
 Aft DoCube           Fri May 27 07:40:00 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:40:00 2022
 Aft UFChkP           Fri May 27 07:42:13 2022      133.36 cpu,      133.39 elapsed
 Aft DecCub           Fri May 27 07:42:18 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 07:42:18 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:42:18 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4189745162
 Aft DoCube           Fri May 27 07:42:19 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_77.chk type G16
 Write formatted file S_77.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:42:34 2022
 Aft UFChkP           Fri May 27 07:44:49 2022      133.44 cpu,      134.08 elapsed
 Aft DecCub           Fri May 27 07:44:54 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 07:44:54 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:44:54 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4998611701
 Aft DoCube           Fri May 27 07:44:54 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:44:54 2022
 Aft UFChkP           Fri May 27 07:47:07 2022      133.37 cpu,      133.36 elapsed
 Aft DecCub           Fri May 27 07:47:12 2022        5.17 cpu,        5.18 elapsed
 Aft Density          Fri May 27 07:47:12 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:47:12 2022        0.02 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4083979706
 Aft DoCube           Fri May 27 07:47:13 2022        0.33 cpu,        0.34 elapsed
 Read checkpoint file S_78.chk type G16
 Write formatted file S_78.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:47:29 2022
 Aft UFChkP           Fri May 27 07:49:44 2022      133.45 cpu,      135.38 elapsed
 Aft DecCub           Fri May 27 07:49:49 2022        5.15 cpu,        5.15 elapsed
 Aft Density          Fri May 27 07:49:49 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:49:49 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4997531631
 Aft DoCube           Fri May 27 07:49:49 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:49:49 2022
 Aft UFChkP           Fri May 27 07:52:01 2022      131.77 cpu,      131.76 elapsed
 Aft DecCub           Fri May 27 07:52:06 2022        5.08 cpu,        5.09 elapsed
 Aft Density          Fri May 27 07:52:06 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:52:06 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4412404845
 Aft DoCube           Fri May 27 07:52:07 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_79.chk type G16
 Write formatted file S_79.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:52:22 2022
 Aft UFChkP           Fri May 27 07:54:36 2022      133.31 cpu,      133.98 elapsed
 Aft DecCub           Fri May 27 07:54:41 2022        5.12 cpu,        5.12 elapsed
 Aft Density          Fri May 27 07:54:41 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:54:41 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000578304
 Aft DoCube           Fri May 27 07:54:42 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:54:42 2022
 Aft UFChkP           Fri May 27 07:56:55 2022      132.92 cpu,      132.93 elapsed
 Aft DecCub           Fri May 27 07:57:00 2022        5.13 cpu,        5.12 elapsed
 Aft Density          Fri May 27 07:57:00 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:57:00 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4005075471
 Aft DoCube           Fri May 27 07:57:00 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_80.chk type G16
 Write formatted file S_80.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:57:16 2022
 Aft UFChkP           Fri May 27 07:59:29 2022      132.86 cpu,      133.75 elapsed
 Aft DecCub           Fri May 27 07:59:34 2022        5.16 cpu,        5.16 elapsed
 Aft Density          Fri May 27 07:59:34 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 07:59:34 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5004357542
 Aft DoCube           Fri May 27 07:59:35 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 07:59:35 2022
 Aft UFChkP           Fri May 27 08:01:48 2022      132.90 cpu,      132.90 elapsed
 Aft DecCub           Fri May 27 08:01:53 2022        5.12 cpu,        5.12 elapsed
 Aft Density          Fri May 27 08:01:53 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:01:53 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3956234368
 Aft DoCube           Fri May 27 08:01:53 2022        0.33 cpu,        0.34 elapsed
 Read checkpoint file S_81.chk type G16
 Write formatted file S_81.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:02:09 2022
 Aft UFChkP           Fri May 27 08:04:23 2022      132.99 cpu,      134.04 elapsed
 Aft DecCub           Fri May 27 08:04:28 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 08:04:28 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:04:28 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4985779879
 Aft DoCube           Fri May 27 08:04:28 2022        0.25 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:04:28 2022
 Aft UFChkP           Fri May 27 08:06:42 2022      133.43 cpu,      133.44 elapsed
 Aft DecCub           Fri May 27 08:06:47 2022        5.13 cpu,        5.14 elapsed
 Aft Density          Fri May 27 08:06:47 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:06:47 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3907824317
 Aft DoCube           Fri May 27 08:06:47 2022        0.33 cpu,        0.34 elapsed
 Read checkpoint file S_82.chk type G16
 Write formatted file S_82.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:07:03 2022
 Aft UFChkP           Fri May 27 08:09:17 2022      133.24 cpu,      134.19 elapsed
 Aft DecCub           Fri May 27 08:09:22 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 08:09:22 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:09:22 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4993905267
 Aft DoCube           Fri May 27 08:09:22 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:09:22 2022
 Aft UFChkP           Fri May 27 08:11:36 2022      133.38 cpu,      133.45 elapsed
 Aft DecCub           Fri May 27 08:11:41 2022        5.15 cpu,        5.15 elapsed
 Aft Density          Fri May 27 08:11:41 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:11:41 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4149769358
 Aft DoCube           Fri May 27 08:11:41 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_83.chk type G16
 Write formatted file S_83.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:11:57 2022
 Aft UFChkP           Fri May 27 08:14:11 2022      133.25 cpu,      134.26 elapsed
 Aft DecCub           Fri May 27 08:14:17 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 08:14:17 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:14:17 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999007889
 Aft DoCube           Fri May 27 08:14:17 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:14:17 2022
 Aft UFChkP           Fri May 27 08:16:31 2022      133.66 cpu,      133.69 elapsed
 Aft DecCub           Fri May 27 08:16:36 2022        5.13 cpu,        5.14 elapsed
 Aft Density          Fri May 27 08:16:36 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:16:36 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4030289935
 Aft DoCube           Fri May 27 08:16:36 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_84.chk type G16
 Write formatted file S_84.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:16:52 2022
 Aft UFChkP           Fri May 27 08:19:06 2022      133.03 cpu,      133.81 elapsed
 Aft DecCub           Fri May 27 08:19:11 2022        5.13 cpu,        5.12 elapsed
 Aft Density          Fri May 27 08:19:11 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:19:11 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4994766308
 Aft DoCube           Fri May 27 08:19:11 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:19:11 2022
 Aft UFChkP           Fri May 27 08:21:25 2022      133.38 cpu,      133.38 elapsed
 Aft DecCub           Fri May 27 08:21:30 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 08:21:30 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:21:30 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3949439309
 Aft DoCube           Fri May 27 08:21:30 2022        0.33 cpu,        0.34 elapsed
 Read checkpoint file S_85.chk type G16
 Write formatted file S_85.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:21:46 2022
 Aft UFChkP           Fri May 27 08:24:00 2022      133.36 cpu,      134.00 elapsed
 Aft DecCub           Fri May 27 08:24:05 2022        5.13 cpu,        5.14 elapsed
 Aft Density          Fri May 27 08:24:05 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:24:05 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000646076
 Aft DoCube           Fri May 27 08:24:05 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:24:05 2022
 Aft UFChkP           Fri May 27 08:26:19 2022      133.28 cpu,      133.40 elapsed
 Aft DecCub           Fri May 27 08:26:24 2022        5.15 cpu,        5.14 elapsed
 Aft Density          Fri May 27 08:26:24 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:26:24 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3950793593
 Aft DoCube           Fri May 27 08:26:24 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_86.chk type G16
 Write formatted file S_86.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:26:40 2022
 Aft UFChkP           Fri May 27 08:28:55 2022      133.27 cpu,      134.89 elapsed
 Aft DecCub           Fri May 27 08:29:00 2022        5.11 cpu,        5.11 elapsed
 Aft Density          Fri May 27 08:29:00 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:29:00 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5001762892
 Aft DoCube           Fri May 27 08:29:00 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:29:00 2022
 Aft UFChkP           Fri May 27 08:31:14 2022      133.87 cpu,      133.87 elapsed
 Aft DecCub           Fri May 27 08:31:19 2022        5.12 cpu,        5.13 elapsed
 Aft Density          Fri May 27 08:31:19 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:31:19 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3959744148
 Aft DoCube           Fri May 27 08:31:19 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_87.chk type G16
 Write formatted file S_87.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:31:35 2022
 Aft UFChkP           Fri May 27 08:33:49 2022      133.21 cpu,      133.80 elapsed
 Aft DecCub           Fri May 27 08:33:54 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 08:33:54 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:33:54 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4998636603
 Aft DoCube           Fri May 27 08:33:54 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:33:54 2022
 Aft UFChkP           Fri May 27 08:36:07 2022      133.14 cpu,      133.14 elapsed
 Aft DecCub           Fri May 27 08:36:13 2022        5.15 cpu,        5.15 elapsed
 Aft Density          Fri May 27 08:36:13 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:36:13 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3981861514
 Aft DoCube           Fri May 27 08:36:13 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_88.chk type G16
 Write formatted file S_88.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:36:29 2022
 Aft UFChkP           Fri May 27 08:38:42 2022      132.76 cpu,      133.31 elapsed
 Aft DecCub           Fri May 27 08:38:47 2022        5.12 cpu,        5.12 elapsed
 Aft Density          Fri May 27 08:38:47 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:38:47 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5002790432
 Aft DoCube           Fri May 27 08:38:48 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:38:48 2022
 Aft UFChkP           Fri May 27 08:41:01 2022      133.34 cpu,      133.66 elapsed
 Aft DecCub           Fri May 27 08:41:06 2022        5.15 cpu,        5.15 elapsed
 Aft Density          Fri May 27 08:41:06 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:41:06 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3970040814
 Aft DoCube           Fri May 27 08:41:07 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_89.chk type G16
 Write formatted file S_89.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:41:23 2022
 Aft UFChkP           Fri May 27 08:43:37 2022      133.45 cpu,      134.19 elapsed
 Aft DecCub           Fri May 27 08:43:42 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 08:43:42 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:43:42 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000274750
 Aft DoCube           Fri May 27 08:43:42 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:43:42 2022
 Aft UFChkP           Fri May 27 08:45:55 2022      133.16 cpu,      133.16 elapsed
 Aft DecCub           Fri May 27 08:46:00 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 08:46:00 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:46:00 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4275278650
 Aft DoCube           Fri May 27 08:46:01 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_90.chk type G16
 Write formatted file S_90.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:46:16 2022
 Aft UFChkP           Fri May 27 08:48:30 2022      133.31 cpu,      133.94 elapsed
 Aft DecCub           Fri May 27 08:48:35 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 08:48:35 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:48:35 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000406264
 Aft DoCube           Fri May 27 08:48:36 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:48:36 2022
 Aft UFChkP           Fri May 27 08:50:49 2022      133.10 cpu,      133.12 elapsed
 Aft DecCub           Fri May 27 08:50:54 2022        5.12 cpu,        5.12 elapsed
 Aft Density          Fri May 27 08:50:54 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:50:54 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4126726447
 Aft DoCube           Fri May 27 08:50:54 2022        0.35 cpu,        0.34 elapsed
 Read checkpoint file S_91.chk type G16
 Write formatted file S_91.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:51:11 2022
 Aft UFChkP           Fri May 27 08:53:24 2022      133.74 cpu,      133.90 elapsed
 Aft DecCub           Fri May 27 08:53:30 2022        5.16 cpu,        5.16 elapsed
 Aft Density          Fri May 27 08:53:30 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:53:30 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999840459
 Aft DoCube           Fri May 27 08:53:30 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:53:30 2022
 Aft UFChkP           Fri May 27 08:55:43 2022      132.71 cpu,      132.71 elapsed
 Aft DecCub           Fri May 27 08:55:48 2022        5.11 cpu,        5.12 elapsed
 Aft Density          Fri May 27 08:55:48 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:55:48 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4097133232
 Aft DoCube           Fri May 27 08:55:48 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_92.chk type G16
 Write formatted file S_92.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:56:04 2022
 Aft UFChkP           Fri May 27 08:58:18 2022      133.43 cpu,      134.19 elapsed
 Aft DecCub           Fri May 27 08:58:23 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 08:58:23 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 08:58:23 2022        0.02 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4996286967
 Aft DoCube           Fri May 27 08:58:23 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 08:58:23 2022
 Aft UFChkP           Fri May 27 09:00:37 2022      133.20 cpu,      133.20 elapsed
 Aft DecCub           Fri May 27 09:00:42 2022        5.12 cpu,        5.13 elapsed
 Aft Density          Fri May 27 09:00:42 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:00:42 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3995546436
 Aft DoCube           Fri May 27 09:00:42 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_93.chk type G16
 Write formatted file S_93.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:00:58 2022
 Aft UFChkP           Fri May 27 09:03:12 2022      133.14 cpu,      133.76 elapsed
 Aft DecCub           Fri May 27 09:03:17 2022        5.13 cpu,        5.13 elapsed
 Aft Density          Fri May 27 09:03:17 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:03:17 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4998053534
 Aft DoCube           Fri May 27 09:03:17 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:03:17 2022
 Aft UFChkP           Fri May 27 09:05:31 2022      133.38 cpu,      133.52 elapsed
 Aft DecCub           Fri May 27 09:05:36 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 09:05:36 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:05:36 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3921017579
 Aft DoCube           Fri May 27 09:05:36 2022        0.35 cpu,        0.34 elapsed
 Read checkpoint file S_94.chk type G16
 Write formatted file S_94.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:05:52 2022
 Aft UFChkP           Fri May 27 09:08:07 2022      133.58 cpu,      134.36 elapsed
 Aft DecCub           Fri May 27 09:08:12 2022        5.18 cpu,        5.18 elapsed
 Aft Density          Fri May 27 09:08:12 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:08:12 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4993261038
 Aft DoCube           Fri May 27 09:08:12 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:08:12 2022
 Aft UFChkP           Fri May 27 09:10:25 2022      133.11 cpu,      133.18 elapsed
 Aft DecCub           Fri May 27 09:10:30 2022        5.13 cpu,        5.14 elapsed
 Aft Density          Fri May 27 09:10:30 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:10:30 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4351782017
 Aft DoCube           Fri May 27 09:10:31 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_95.chk type G16
 Write formatted file S_95.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:10:47 2022
 Aft UFChkP           Fri May 27 09:13:02 2022      133.55 cpu,      134.43 elapsed
 Aft DecCub           Fri May 27 09:13:07 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 09:13:07 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:13:07 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4995993167
 Aft DoCube           Fri May 27 09:13:07 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:13:07 2022
 Aft UFChkP           Fri May 27 09:15:20 2022      133.20 cpu,      133.20 elapsed
 Aft DecCub           Fri May 27 09:15:26 2022        5.12 cpu,        5.13 elapsed
 Aft Density          Fri May 27 09:15:26 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:15:26 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3978116236
 Aft DoCube           Fri May 27 09:15:26 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_96.chk type G16
 Write formatted file S_96.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:15:42 2022
 Aft UFChkP           Fri May 27 09:18:06 2022      133.65 cpu,      144.32 elapsed
 Aft DecCub           Fri May 27 09:18:11 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 09:18:11 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:18:11 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4996849741
 Aft DoCube           Fri May 27 09:18:12 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:18:12 2022
 Aft UFChkP           Fri May 27 09:20:45 2022      133.44 cpu,      153.51 elapsed
 Aft DecCub           Fri May 27 09:20:50 2022        5.13 cpu,        5.14 elapsed
 Aft Density          Fri May 27 09:20:50 2022        0.01 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:20:50 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3969542287
 Aft DoCube           Fri May 27 09:20:51 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_97.chk type G16
 Write formatted file S_97.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:21:07 2022
 Aft UFChkP           Fri May 27 09:23:51 2022      133.12 cpu,      164.74 elapsed
 Aft DecCub           Fri May 27 09:23:57 2022        5.58 cpu,        5.57 elapsed
 Aft Density          Fri May 27 09:23:57 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:23:57 2022        0.01 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5000359296
 Aft DoCube           Fri May 27 09:23:57 2022        0.23 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:23:57 2022
 Aft UFChkP           Fri May 27 09:26:11 2022      133.35 cpu,      133.51 elapsed
 Aft DecCub           Fri May 27 09:26:16 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 09:26:16 2022        0.01 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:26:16 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4063611878
 Aft DoCube           Fri May 27 09:26:16 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_98.chk type G16
 Write formatted file S_98.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:26:32 2022
 Aft UFChkP           Fri May 27 09:28:46 2022      133.30 cpu,      134.25 elapsed
 Aft DecCub           Fri May 27 09:28:52 2022        5.13 cpu,        5.14 elapsed
 Aft Density          Fri May 27 09:28:52 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:28:52 2022        0.01 cpu,        0.01 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5007497004
 Aft DoCube           Fri May 27 09:28:52 2022        0.24 cpu,        0.24 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:28:52 2022
 Aft UFChkP           Fri May 27 09:31:05 2022      133.11 cpu,      133.11 elapsed
 Aft DecCub           Fri May 27 09:31:10 2022        5.14 cpu,        5.14 elapsed
 Aft Density          Fri May 27 09:31:10 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:31:10 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.3958128900
 Aft DoCube           Fri May 27 09:31:10 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_99.chk type G16
 Write formatted file S_99.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:31:26 2022
 Aft UFChkP           Fri May 27 09:33:41 2022      133.45 cpu,      134.24 elapsed
 Aft DecCub           Fri May 27 09:33:46 2022        5.15 cpu,        5.14 elapsed
 Aft Density          Fri May 27 09:33:46 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:33:46 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.5002577076
 Aft DoCube           Fri May 27 09:33:46 2022        0.24 cpu,        0.25 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:33:46 2022
 Aft UFChkP           Fri May 27 09:35:59 2022      133.27 cpu,      133.27 elapsed
 Aft DecCub           Fri May 27 09:36:04 2022        5.11 cpu,        5.11 elapsed
 Aft Density          Fri May 27 09:36:04 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:36:04 2022        0.00 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4073293767
 Aft DoCube           Fri May 27 09:36:05 2022        0.34 cpu,        0.34 elapsed
 Read checkpoint file S_100.chk type G16
 Write formatted file S_100.fchk
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:36:21 2022
 Aft UFChkP           Fri May 27 09:38:35 2022      133.45 cpu,      134.63 elapsed
 Aft DecCub           Fri May 27 09:38:40 2022        5.15 cpu,        5.14 elapsed
 Aft Density          Fri May 27 09:38:40 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:38:40 2022        0.00 cpu,        0.00 elapsed
 There are a total of      108486 grid points.
 ElSum from         orbitals=        0.4999575412
 Aft DoCube           Fri May 27 09:38:41 2022        0.25 cpu,        0.25 elapsed
 Will use up to     4 threads.
 Top CubeGen          Fri May 27 09:38:41 2022
 Aft UFChkP           Fri May 27 09:40:54 2022      133.32 cpu,      133.32 elapsed
 Aft DecCub           Fri May 27 09:40:59 2022        5.13 cpu,        5.14 elapsed
 Aft Density          Fri May 27 09:40:59 2022        0.00 cpu,        0.00 elapsed
 Bef DoCube           Fri May 27 09:40:59 2022        0.01 cpu,        0.01 elapsed
 There are a total of      163968 grid points.
 ElSum from         orbitals=        0.4048145184
 Aft DoCube           Fri May 27 09:40:59 2022        0.35 cpu,        0.34 elapsed
