Dimension = 9000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (648.0,0.65)
0.01 1.8
Dimension = 9000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (648.0,0.65)
0.1 1.8
Dimension = 9000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (648.0,0.65)
0.2 1.8
Dimension = 9000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (648.0,0.65)
0.3 1.8
Dimension = 9000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (648.0,0.65)
0.4 1.8
