slurmstepd: error: task/cgroup: unable to add task[pid=16533] to memory cg '(null)'
compute_dipole.py:427: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  header = np.array([ np.array(j.split()) for j in open(f"../TD-DFT/NTOs/S_1.HOTO.cube","r").readlines()[1:6] ])
Reading Upol file 0 of 1
NFock = 5
	Starting to Read NTO Files.
	NAtoms   = 84
	TD Grid  = 1144000
	Nx Ny Nz = 260 110 40
	Lx Ly Lz = 45.043928 17.511355 6.517836 A
	dLx dLy dLz = 0.333333 0.333333 0.333333 A
	Volume   = 5141.14007360924 A^3
	Memory size of transition density array in (MB, GB): (8072.06,8.07)
I FINISHED READING NTOs.
Writing NTO file. p: 0-->0, eta = 0.06
Writing NTO file. p: 0-->0, eta = 0.06
Writing NTO file. p: 0-->1, eta = 0.06
Writing NTO file. p: 0-->1, eta = 0.06
Writing NTO file. p: 0-->2, eta = 0.06
Writing NTO file. p: 0-->2, eta = 0.06
Writing NTO file. p: 0-->3, eta = 0.06
Writing NTO file. p: 0-->3, eta = 0.06
Writing NTO file. p: 0-->4, eta = 0.06
Writing NTO file. p: 0-->4, eta = 0.06
Writing NTO file. p: 0-->5, eta = 0.06
Writing NTO file. p: 0-->5, eta = 0.06
Writing NTO file. p: 0-->6, eta = 0.06
Writing NTO file. p: 0-->6, eta = 0.06
Writing NTO file. p: 0-->7, eta = 0.06
Writing NTO file. p: 0-->7, eta = 0.06
Writing NTO file. p: 0-->8, eta = 0.06
Writing NTO file. p: 0-->8, eta = 0.06
Writing NTO file. p: 0-->9, eta = 0.06
Writing NTO file. p: 0-->9, eta = 0.06
