Dimension = 10000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (800.0,0.8)
0.01 1.8
Dimension = 10000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (800.0,0.8)
0.1 1.8
Dimension = 10000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (800.0,0.8)
0.3 1.8
Dimension = 10000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (800.0,0.8)
0.2 1.8
Dimension = 10000
	WARNING!!! Large Matrix
	Memory size of numpy array in (MB, GB): (800.0,0.8)
0.4 1.8
